const cocktailDataRaw = [
  {
    strDrink: "Xav'tail",
    strCategory: "Obnoxious drink",
    strAlcoholic: "Alcoholic",
    strGlass: "Wild Glass",
    strInstructions:
      "Fetch the Xavier with extreme caution, you have keep it cool to be able to pour it wildy inside the Wild glass. There is no guarantee the Xavier won't start a livecoding. Be aware that the Xav'tail is a dangerous and unpleasant drink, you might get a strong headache and you might React with Express dreams.",
    strDrinkThumb:
      "https://ca.slack-edge.com/T6SG2QGG2-UHBQ50AV8-7fa84665b54b-512",
    strIngredient1: "Unix",
    strIngredient2: "Slacking",
    strIngredient3: "Patience",
    strIngredient4: "Honda",
    strIngredient5: "",
    strIngredient6: "",
    strIngredient7: "",
    strIngredient8: "",
    strIngredient9: "",
    strIngredient10: "",
    strIngredient11: "",
    strIngredient12: "",
    strIngredient13: "",
    strIngredient14: "",
    strIngredient15: "",
    strMeasure1: "42 bugs",
    strMeasure2: "69 shades",
    strMeasure3: "Ultra mega huge dose",
    strMeasure4: "1 Boar",
    strMeasure5: "",
    strMeasure6: "",
    strMeasure7: "",
    strMeasure8: "",
    strMeasure9: "",
    strMeasure10: "",
    strMeasure11: "",
    strMeasure12: "",
    strMeasure13: "",
    strMeasure14: "",
    strMeasure15: "",
  },
];

export default cocktailDataRaw;
